# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: 'Add conda to PATH'

- bash: conda env create --yes --quiet --force --file environment-dev.yml
  displayName: 'Create Anaconda environment'

- bash: |
    source activate dev
    coverage run -m pytest
  displayName: 'Run the tests and check for test coverage'

- bash: |
    source activate dev
    coverage report -m
  displayName: 'Generate test coverage report'

- bash: |
    source activate dev
    codecov
  displayName: 'Upload the report to codecov'

- bash: |
    source activate dev
    flake8
  displayName: 'Enforce code style'

- bash: |
    source activate dev
    make -C docs html
  displayName: 'Build the documentation'
