name: dev
channels:
  - defaults
  - conda-forge
  - diffpy
dependencies:
  - python >=3.7
  - setuptools
  - versioneer
  - bson
  - pyyaml
  - pandas
  - pyperclip
  - streamz
  - diffpy-cmi
  - xpdtools
  - codecov
  - coverage
  - flake8
  - pytest
  - pytest-azurepipelines
  - sphinx
  - ipython
  - numpydoc
  - sphinx-copybutton
  - sphinx_rtd_theme
