[workspace]
authors = ["Thomas A Caswell <tcaswell@bnl.gov>"]
channels = ["conda-forge"]
name = "PDFstream"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.13,<3.14"
bluesky-base = ">=1.15.1,<2"
fire = ">=0.7.1,<0.8"
pyfai = ">=2026.3.0,<2027"
tiled = ">=0.2.9,<0.3"
databroker = ">=2.0.0,<3"
suitcase-csv = ">=0.3.0,<0.4"
suitcase-json-metadata = ">=0.2.1,<0.3"
scikit-beam = ">=0.0.27,<0.0.28"
suitcase-tiff = ">=0.4.0,<0.5"
xpdview = ">=0.5.0,<0.6"
"diffpy.pdfgui" = ">=3.1.0,<4"
xray-vision = ">=0.1.1,<0.2"
setuptools = ">=82.0.1,<83"
wheel = ">=0.47.0,<0.48"
nslsii = ">=0.11.9,<0.12"
bluesky-widgets = ">=0.0.18,<0.0.19"

[pypi-dependencies]
pdfstream = { git = "https://github.com/NSLS-II-PDF/pdfstream.git", rev="v0.5.x" }

[tasks.server]
# args = ["ini"]
cmd = "run_server"
