# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.3
        with:
          # Whether to activate the conda base env (Default: 'true')
          activate-conda: true # optional, default is true
          # If conda should be updated before running other commands (Default: 'false')
          update-conda: false # optional, default is false
          # Python version which should be installed with conda (default: 'Default')
          python-version: 3.7 # optional, default is default
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: conda-forge, diffpy # optional, default is

      - uses: actions/checkout@v2
        with:
          repository: st3107/diffpy.pdfgetx-whl
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: install diffpy.pdfgetx
        run: python -m pip install diffpy.pdfgetx-*.whl

      - uses: actions/checkout@v2

      - name: isntall requirements
        run: conda install --file requirements/build.txt --file requirements/run.txt --file requirements/test.txt

      - name: install pdfstream
        run: python -m pip install -e .

      - name: run the tests and check for test coverage
        run: coverage run -m pytest tests --showlocals

      - name: generate test coverage report and upload to codecov
        run: |
          coverage report -m
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

      - name: check code style
        run: flake8

  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Only publish if a tag starting with v is pushed
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')

    # Require passing the test
    needs: test

    env:
      CONDA_USER_NAME: st3107
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.3
        with:
          # Whether to activate the conda base env (Default: 'true')
          activate-conda: true # optional, default is true
          # If conda should be updated before running other commands (Default: 'false')
          update-conda: false # optional, default is false
          # Python version which should be installed with conda (default: 'Default')
          python-version: 3.7 # optional, default is default
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: conda-forge, diffpy # optional, default is

      - uses: actions/checkout@v2
        with:
          repository: st3107/diffpy.pdfgetx-whl
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: install diffpy.pdfgetx
        run: python -m pip install diffpy.pdfgetx-*.whl

      - uses: actions/checkout@v2

      - name: install requirements
        run: conda install --file requirements/build.txt --file requirements/run.txt --file requirements/docs.txt

      - name: install pdfstream
        run: python -m pip install .

      - name: build documents
        run: make -C docs html

      - name: deploy to github pages
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          # In order for GitHub to trigger the rebuild of your page you must provide the action with the repositories provided GitHub token.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This is the branch you wish to deploy to, for example gh-pages or docs.
          BRANCH: gh-pages
          # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
          FOLDER: docs/build/html
          # The base branch of your repository which you would like to checkout prior to deploying. This defaults to the current commit SHA that triggered the build followed by master if it does not exist. This is useful for making deployments from another branch, and also may be necessary when using a scheduled job.
