name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: configure conda
        run: |
          conda config --append channels nsls2forge
          conda config --append channels conda-forge

      - name: install requirements
        run: >-
          conda create -n test --file requirements/build.txt --file requirements/run.txt --file
          requirements/test.txt --quiet --yes

      - uses: actions/checkout@v2
        with:
          repository: st3107/diffpy.pdfgetx-whl
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: install diffpy.pdfgetx
        run: |
          source activate test
          python -m pip install *.whl

      - uses: actions/checkout@v2

      - name: install pdfstream
        run: |
          source activate test
          python -m pip install .

      - name: run the tests and check for test coverage
        run: |
          source activate test
          coverage run -m pytest tests --showlocals

      - name: generate test coverage report and upload to codecov
        run: |
          source activate test
          coverage report -m
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

      - name: check code style
        run: |
          source activate test
          flake8

      - name: build documents
        run: |
          source activate test
          make -C docs html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
